# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

"""
Task definitions for the ACRE (Active Customer Retention Engine) Environment.

Defines three graded tasks with increasing difficulty:
- Task 1 (Easy): "Obvious Saves" - High CLV, easy competitor rates
- Task 2 (Medium): "Margin Squeeze" - Aggressive competitor rates
- Task 3 (Hard): "VIP Triage" - Mixed customers with tight budget
"""

from dataclasses import dataclass, field
from typing import List, Optional
import random
import os
import sqlite3

try:
    from ..models import ChurnReason, CustomerObservation
except ImportError:
    from models import ChurnReason, CustomerObservation


@dataclass
class CustomerProfile:
    """Configuration for generating a customer in a task scenario."""
    
    customer_id: str
    clv_range: tuple  # (min, max) CLV
    monthly_revenue_range: tuple
    tenure_range: tuple  # (min, max) months
    churn_risk_range: tuple  # (min, max) risk score
    primary_reason: ChurnReason
    current_rate: float
    competitor_rate: float
    monthly_fee: float
    sentiment_range: tuple = (-0.3, 0.3)
    is_vip: bool = False  # Special flag for Hard task VIP
    is_negative_value: bool = False  # Flag for unprofitable customers


@dataclass
class TaskConfig:
    """Configuration for a graded task scenario."""
    
    task_id: str
    name: str
    difficulty: str  # "easy", "medium", "hard"
    description: str
    initial_budget: float
    customer_profiles: List[CustomerProfile]
    
    # Grading criteria
    passing_roi_threshold: float = 0.0  # Minimum ROI to pass
    optimal_roi_estimate: float = 1000.0  # Estimated optimal ROI for normalization
    
    # Special grading flags
    require_vip_save: bool = False  # Hard task: must save VIP
    penalize_negative_value_offers: bool = False  # Hard task: don't waste on unprofitable


# Module-level DB path override. Set by the unified server.
_DB_PATH_OVERRIDE: Optional[str] = None


def _load_profiles_from_bank_churn_db() -> List[CustomerProfile]:
    """
    Build hard-task customer profiles from Task 1 + Task 2 outputs generated by bank_churn_env.
    Falls back to static task data when DB rows are unavailable.
    """
    if _DB_PATH_OVERRIDE and os.path.exists(_DB_PATH_OVERRIDE):
        db_path = _DB_PATH_OVERRIDE
    else:
        # Search in cwd first, then in bank_churn_env/ relative to this file
        candidates = [
            os.path.join(os.getcwd(), "bank_ops.db"),
            os.path.join(
                os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
                "bank_churn_env",
                "bank_ops.db",
            ),
            os.path.join(
                os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
                "bank_ops.db",
            ),
        ]
        db_path = None
        for c in candidates:
            if os.path.exists(c):
                db_path = c
                break
        if db_path is None:
            return []

    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    try:
        cur = conn.cursor()

        cur.execute("SELECT episode_id FROM task1_predictions ORDER BY created_at DESC LIMIT 1")
        task1_row = cur.fetchone()
        cur.execute("SELECT episode_id FROM task2_deployment ORDER BY created_at DESC LIMIT 1")
        task2_row = cur.fetchone()

        if not task1_row or not task2_row:
            return []

        task1_episode = str(task1_row["episode_id"])
        task2_episode = str(task2_row["episode_id"])

        cur.execute(
            """
            SELECT
                t2.customer_id,
                t2.offer_value,
                t2.campaign_source,
                t1.true_tier,
                t1.predicted_tier,
                t1.step_reward
            FROM task2_deployment t2
            LEFT JOIN task1_predictions t1
              ON t1.customer_id = t2.customer_id
             AND t1.episode_id = ?
            WHERE t2.episode_id = ?
            ORDER BY
                CASE COALESCE(t1.true_tier, 'not_at_risk')
                    WHEN 'high_risk' THEN 1
                    WHEN 'medium_risk' THEN 2
                    WHEN 'low_risk' THEN 3
                    ELSE 4
                END,
                t2.offer_value DESC
            """,
            (task1_episode, task2_episode),
        )
        rows = [dict(r) for r in cur.fetchall()]
    finally:
        conn.close()

    if not rows:
        return []

    profiles: List[CustomerProfile] = []
    top_index = min(4, len(rows) - 1)

    def _tier_to_reason(tier: str) -> ChurnReason:
        if tier == "high_risk":
            return ChurnReason.HIGH_COMPETITOR_RATE
        if tier == "medium_risk":
            return ChurnReason.FEE_SENSITIVITY
        if tier == "low_risk":
            return ChurnReason.INACTIVE_ACCOUNT
        return ChurnReason.LIFE_EVENT

    for idx, row in enumerate(rows[:6]):
        tier = str(row.get("true_tier") or row.get("predicted_tier") or "low_risk")
        offer_value = float(row.get("offer_value", 0.0))
        source = str(row.get("campaign_source", "retention"))
        step_reward = float(row.get("step_reward", 0.0))

        risk_map = {
            "high_risk": (0.72, 0.92),
            "medium_risk": (0.55, 0.75),
            "low_risk": (0.35, 0.55),
            "not_at_risk": (0.20, 0.35),
        }

        is_vip = idx == top_index
        is_negative = tier in {"low_risk", "not_at_risk"} and offer_value < 4000

        base_clv = max(200.0, offer_value * (3.5 if tier in {"high_risk", "medium_risk"} else 1.2))
        if is_vip:
            base_clv = max(base_clv, 22000.0)
        if is_negative:
            base_clv = min(base_clv, 900.0)

        monthly_fee = 20.0 if source == "retention" else (30.0 if source == "credit_card" else 40.0)
        current_rate = 0.07 if source == "retention" else (0.08 if source == "credit_card" else 0.09)
        competitor_rate = max(0.02, current_rate - 0.02)

        profiles.append(
            CustomerProfile(
                customer_id=str(row.get("customer_id", f"DYN_{idx+1:03d}")),
                clv_range=(round(base_clv * 0.9, 2), round(base_clv * 1.1, 2)),
                monthly_revenue_range=(
                    round(max(10.0, base_clv * 0.02), 2),
                    round(max(20.0, base_clv * 0.03), 2),
                ),
                tenure_range=(6, 84 if is_vip else 48),
                churn_risk_range=risk_map.get(tier, (0.35, 0.55)),
                primary_reason=_tier_to_reason(tier),
                current_rate=current_rate,
                competitor_rate=competitor_rate,
                monthly_fee=monthly_fee,
                sentiment_range=(-0.5, 0.2) if step_reward < 0 else (-0.2, 0.4),
                is_vip=is_vip,
                is_negative_value=is_negative,
            )
        )

    return profiles




def create_hard_task() -> TaskConfig:
    """
    Task 3: VIP Triage
    
    Mixed queue with negative-value customers and one massive VIP.
    Very tight budget forces prioritization. The agent must:
    1. Recognize and skip negative-value customers
    2. Conserve budget for the VIP
    3. Make a compelling offer to retain the VIP
    
    Scoring heavily weights VIP retention.
    """
    dynamic_customers = _load_profiles_from_bank_churn_db()
    if dynamic_customers:
        return TaskConfig(
            task_id="task3_retention_orchestration",
            name="Task 3 Retention Orchestration",
            difficulty="hard",
            description=(
                "DB-driven hard task generated from bank_churn_env outputs. "
                "Use Task 1 + Task 2 data to prioritize high-value customers and protect VIP retention."
            ),
            initial_budget=800.0,
            customer_profiles=dynamic_customers,
            passing_roi_threshold=5000.0,
            optimal_roi_estimate=15000.0,
            require_vip_save=True,
            penalize_negative_value_offers=True,
        )

    customers = [
        # Negative value customer 1 - money loser
        CustomerProfile(
            customer_id="HARD_C001_NEG",
            clv_range=(200, 400),  # Very low CLV
            monthly_revenue_range=(15, 25),
            tenure_range=(3, 8),
            churn_risk_range=(0.85, 0.95),
            primary_reason=ChurnReason.FEE_SENSITIVITY,
            current_rate=0.04,
            competitor_rate=0.025,  # Very aggressive
            monthly_fee=45.0,
            sentiment_range=(-0.7, -0.4),
            is_negative_value=True
        ),
        # Negative value customer 2
        CustomerProfile(
            customer_id="HARD_C002_NEG",
            clv_range=(150, 300),
            monthly_revenue_range=(10, 20),
            tenure_range=(2, 6),
            churn_risk_range=(0.88, 0.96),
            primary_reason=ChurnReason.SERVICE_DISSATISFACTION,
            current_rate=0.035,
            competitor_rate=0.02,
            monthly_fee=50.0,
            sentiment_range=(-0.8, -0.5),
            is_negative_value=True
        ),
        # Marginal customer - borderline
        CustomerProfile(
            customer_id="HARD_C003_MARG",
            clv_range=(800, 1200),
            monthly_revenue_range=(50, 80),
            tenure_range=(6, 12),
            churn_risk_range=(0.70, 0.82),
            primary_reason=ChurnReason.HIGH_COMPETITOR_RATE,
            current_rate=0.055,
            competitor_rate=0.03,
            monthly_fee=35.0,
            sentiment_range=(-0.5, -0.2),
            is_negative_value=False
        ),
        # Negative value customer 3
        CustomerProfile(
            customer_id="HARD_C004_NEG",
            clv_range=(100, 250),
            monthly_revenue_range=(8, 18),
            tenure_range=(1, 4),
            churn_risk_range=(0.90, 0.98),
            primary_reason=ChurnReason.INACTIVE_ACCOUNT,
            current_rate=0.03,
            competitor_rate=0.018,
            monthly_fee=55.0,
            sentiment_range=(-0.85, -0.6),
            is_negative_value=True
        ),
        # THE VIP - must save this one!
        CustomerProfile(
            customer_id="HARD_C005_VIP",
            clv_range=(25000, 30000),  # Massive CLV!
            monthly_revenue_range=(800, 1000),
            tenure_range=(60, 96),  # Long tenure
            churn_risk_range=(0.55, 0.68),  # Moderate risk
            primary_reason=ChurnReason.RATE_SHOPPING,
            current_rate=0.065,
            competitor_rate=0.04,
            monthly_fee=15.0,  # Premium customer, low fee
            sentiment_range=(-0.2, 0.2),
            is_vip=True
        ),
        # One more negative value after VIP (to catch agents who don't skip)
        CustomerProfile(
            customer_id="HARD_C006_NEG",
            clv_range=(180, 350),
            monthly_revenue_range=(12, 22),
            tenure_range=(2, 5),
            churn_risk_range=(0.87, 0.94),
            primary_reason=ChurnReason.LIFE_EVENT,
            current_rate=0.038,
            competitor_rate=0.022,
            monthly_fee=48.0,
            sentiment_range=(-0.75, -0.45),
            is_negative_value=True
        ),
    ]
    
    return TaskConfig(
        task_id="task3_retention_orchestration",
        name="Task 3 Retention Orchestration",
        difficulty="hard",
        description=(
            "A mixed queue with several unprofitable customers and one high-value VIP. "
            "Budget is very tight ($800). You must recognize which customers to skip "
            "to save budget for the VIP. Wasting budget on low-value customers will "
            "leave you unable to retain the VIP - resulting in massive CLV loss."
        ),
        initial_budget=800.0,  # Very tight!
        customer_profiles=customers,
        passing_roi_threshold=5000.0,  # High bar - must save VIP
        optimal_roi_estimate=15000.0,
        require_vip_save=True,
        penalize_negative_value_offers=True,
    )


def generate_customer_from_profile(
    profile: CustomerProfile, 
    remaining_budget: float,
    queue_position: int,
    total_customers: int,
    task_id: str,
    task_difficulty: str,
    seed: Optional[int] = None
) -> CustomerObservation:
    """
    Generate a CustomerObservation from a profile with randomized values.
    
    Args:
        profile: CustomerProfile defining the customer's characteristics
        remaining_budget: Current remaining budget for the episode
        queue_position: 1-indexed position in the queue
        total_customers: Total number of customers in queue
        task_id: Identifier for the current task
        task_difficulty: Difficulty level of the task
        seed: Optional random seed for reproducibility
        
    Returns:
        CustomerObservation ready for the agent
    """
    if seed is not None:
        random.seed(seed)
    
    clv = random.uniform(*profile.clv_range)
    monthly_rev = random.uniform(*profile.monthly_revenue_range)
    tenure = random.randint(*profile.tenure_range)
    churn_risk = random.uniform(*profile.churn_risk_range)
    sentiment = random.uniform(*profile.sentiment_range)
    
    # Potentially add secondary reasons
    secondary_reasons = []
    all_reasons = list(ChurnReason)
    all_reasons.remove(profile.primary_reason)
    if random.random() > 0.5:
        secondary_reasons.append(random.choice(all_reasons))
    
    return CustomerObservation(
        customer_id=profile.customer_id,
        customer_lifetime_value=round(clv, 2),
        monthly_revenue=round(monthly_rev, 2),
        account_tenure_months=tenure,
        churn_risk_score=round(churn_risk, 3),
        primary_churn_reason=profile.primary_reason,
        secondary_churn_reasons=secondary_reasons,
        current_rate=profile.current_rate,
        competitor_best_rate=profile.competitor_rate,
        current_monthly_fee=profile.monthly_fee,
        sentiment_score=round(sentiment, 2),
        remaining_budget=round(remaining_budget, 2),
        queue_position=queue_position,
        total_customers=total_customers,
        task_id=task_id,
        task_difficulty=task_difficulty,
        done=False,
        reward=0.0,
    )


def get_task(task_id: str) -> TaskConfig:
    """Get the task configuration (only task3_retention_orchestration is available)."""
    if task_id != "task3_retention_orchestration":
        raise ValueError(
            f"Unknown task: {task_id}. Available: ['task3_retention_orchestration']"
        )
    return create_hard_task()


def list_tasks() -> List[str]:
    """List available task IDs."""
    return ["task3_retention_orchestration"]
